### ISSUE TITLE
雅典娜的固件无法运行lucky和全能推送

### ISSUE THREAD

**Issue by popeshaka** [ZqinKing/wrt_relese#10]
如题，表现为点保存启动，还是提示未运行

**Comment by ZqinKing** [comment]
> 如题，表现为点保存启动，还是提示未运行

雅典娜和亚瑟的lucky都测试了，均可以正常使用。
全能推送是个什么插件？

**Comment by popeshaka** [comment]
> > 如题，表现为点保存启动，还是提示未运行
> 
> 雅典娜和亚瑟的lucky都测试了，均可以正常使用。 全能推送是个什么插件？

进istore商店，看下就能找到全能推送。
libwrt固件下lucky就无法运行，immwrt下能运行。
但immwrt固件的很多设置，必须保存后重启才会生效，已经反复测试了

**Comment by ZqinKing** [comment]
> > > 如题，表现为点保存启动，还是提示未运行
> > 
> > 
> > 雅典娜和亚瑟的lucky都测试了，均可以正常使用。 全能推送是个什么插件？
> 
> 进istore商店，看下就能找到全能推送。 libwrt固件下lucky就无法运行，immwrt下能运行。 但immwrt固件的很多设置，必须保存后重启才会生效，已经反复测试了

ok，LiBwrt的lucky抽空我看看。imm哪些设置需要重启生效？

**Comment by ZqinKing** [comment]
全能推送也是了，单独进行发送测试是可以的，这个只能去插件源码进行反馈修复。

**Comment by ZqinKing** [comment]
![image](https://github.com/user-attachments/assets/7776ad68-133a-4b02-a10a-7a7624556918)
LiBwrt的lucky也测试了，可以正常运行。

**Comment by popeshaka** [comment]
> ![image](https://private-user-images.githubusercontent.com/40748028/397895067-7776ad68-133a-4b02-a10a-7a7624556918.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDI2MTcsIm5iZiI6MTczNDc0MjMxNywicGF0aCI6Ii80MDc0ODAyOC8zOTc4OTUwNjctNzc3NmFkNjgtMTMzYS00YjAyLWExMGEtN2E3NjI0NTU2OTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAwNTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMjRiYTk0NzI0ZjBmMWFlMGI2OTlhNGE2MWZkNDY4OGM2ZjZjMDk5MGUyYTM5MzI0MmVmMjkzZDkwMDNiYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AHJ30n-2R_Z1lLlM_biH_KeJuJgVAw5HtrlFZ8TnP9M) LiBwrt的lucky也测试了，可以正常运行。

奇了怪了，你的libwrt的lucky界面和我的不一样，难怪我不能启动，immwrt下的界面是这个。ipv6的疑问我在恩山有跟进，去那里吧
