### ISSUE TITLE
能否添加DAED需要的内核？

### ISSUE THREAD

**Issue by shookgao** [ZqinKing/wrt_relese#11]
大佬，luci-app-daed需要的内核如下：
```bash
CONFIG_DEVEL=y
CONFIG_KERNEL_DEBUG_INFO=y
CONFIG_KERNEL_DEBUG_INFO_REDUCED=n
CONFIG_KERNEL_DEBUG_INFO_BTF=y
CONFIG_KERNEL_CGROUPS=y
CONFIG_KERNEL_CGROUP_BPF=y
CONFIG_KERNEL_BPF_EVENTS=y
CONFIG_BPF_TOOLCHAIN_HOST=y
CONFIG_KERNEL_XDP_SOCKETS=y
CONFIG_PACKAGE_kmod-xdp-sockets-diag=y
```
但我把这些配置加入到deconfig里面的时候，编译始终不成功，大佬能看看是什么问题吗？

**Comment by ZqinKing** [comment]
> 大佬，luci-app-daed需要的内核如下：
> 
> ```shell
> CONFIG_DEVEL=y
> CONFIG_KERNEL_DEBUG_INFO=y
> CONFIG_KERNEL_DEBUG_INFO_REDUCED=n
> CONFIG_KERNEL_DEBUG_INFO_BTF=y
> CONFIG_KERNEL_CGROUPS=y
> CONFIG_KERNEL_CGROUP_BPF=y
> CONFIG_KERNEL_BPF_EVENTS=y
> CONFIG_BPF_TOOLCHAIN_HOST=y
> CONFIG_KERNEL_XDP_SOCKETS=y
> CONFIG_PACKAGE_kmod-xdp-sockets-diag=y
> ```
> 
> 但我把这些配置加入到deconfig里面的时候，编译始终不成功，大佬能看看是什么问题吗？

源码里的大鹅被我删了，在update.sh脚本中搜一下，注释相关脚本，应该就能正常添加了。

**Comment by shookgao** [comment]
我把下面的DAE相关的删除掉了，但是好像还是不行

**Comment by ZqinKing** [comment]
> 我把下面的DAE相关的删除掉了，但是好像还是不行
> 
> ```shell
>     local luci_packages=(
>         "luci-app-passwall" "luci-app-smartdns" "luci-app-ddns-go" "luci-app-rclone"
>         "luci-app-ssr-plus" "luci-app-vssr" "luci-theme-argon" "luci-app-daed" "luci-app-dae"
>         "luci-app-alist" "luci-app-argon-config" "luci-app-homeproxy" "luci-app-haproxy-tcp"
>         "luci-app-openclash" "luci-app-mihomo"
>     )
>     local packages_net=(
>         "haproxy" "xray-core" "xray-plugin" "dns2tcp" "dns2socks" "alist" "hysteria"
>         "smartdns" "mosdns" "adguardhome" "ddns-go" "naiveproxy" "shadowsocks-rust"
>         "sing-box" "v2ray-core" "v2ray-geodata" "v2ray-plugin" "tuic-client"
>         "chinadns-ng" "ipt2socks" "tcping" "trojan-plus" "simple-obfs"
>         "shadowsocksr-libev" "dae" "daed" "mihomo" "geoview"
>     )
>     local small8_packages=(
>         "ppp" "firewall" "dae" "daed" "daed-next" "libnftnl" "nftables" "dnsmasq"
>     )
> ```
> 
> 编译后安装还是提示： ![image](https://private-user-images.githubusercontent.com/8251819/398120514-0853ef45-1feb-4476-8c54-1bbe41641e20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwODg2NzgsIm5iZiI6MTczNTA4ODM3OCwicGF0aCI6Ii84MjUxODE5LzM5ODEyMDUxNC0wODUzZWY0NS0xZmViLTQ0NzYtOGM1NC0xYmJlNDE2NDFlMjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMDA1OTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg4YmI2OWU2Y2U1ZTlhNmZlOWYwNmM3OTNmODBjMWY1MDMxZjU0NWRlMzU3ZWFjMzUyNDIxNDhkNGI3MzhjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QVWn1c0-JzCkR2d6pJvSW6NjYnwS1lE90e3SfW7zh6I)

缺一些内核依赖，需要在.config中补上。
