### ISSUE TITLE
24.11.29版的几个问题

### ISSUE THREAD

**Issue by FlyingHD** [ZqinKing/wrt_relese#7]
Hi Author,
LibWrt我用的很开心，但是发现几个问题跟您反馈一下

设备：
雅典娜128G （AX6600）
安装背景：
从之前24.10版本升级到11.29版，发现几个问题
问题：
1. istore安装软件，如果先安装了易有云，再安装aira2插件，安装失败，提示已经安装了易有云，code 1.  同样的情况下，安装流量监控插件，失败，报错相同。手动卸载易有云，安装aira2成功，安装流量监控成功
2. 开启openclash后，台式机右下角有线连接的网络图标有概率会提示无internet，图标为地球，但此时实际能上网，内网外网都没问题。解决办法是关闭openclash服务，台式机连接提示有internet，图标变为电脑方框，此时再启动Openclash服务，网络访问和图标提示都恢复正常。这个问题不影响浏览器开网页，但是会影响一些需要同步的程序，比如onedrive, 他认为当前无网，就自动停止同步。

**Comment by ZqinKing** [comment]
> Hi Author, LibWrt我用的很开心，但是发现几个问题跟您反馈一下
> 
> 设备： 雅典娜128G （AX6600） 安装背景： 从之前24.10版本升级到11.29版，发现几个问题 问题：
> 
> 1. istore安装软件，如果先安装了易有云，再安装aira2插件，安装失败，提示已经安装了易有云，code 1.  同样的情况下，安装流量监控插件，失败，报错相同。手动卸载易有云，安装aira2成功，安装流量监控成功
> 2. 开启openclash后，台式机右下角有线连接的网络图标有概率会提示无internet，图标为地球，但此时实际能上网，内网外网都没问题。解决办法是关闭openclash服务，台式机连接提示有internet，图标变为电脑方框，此时再启动Openclash服务，网络访问和图标提示都恢复正常。这个问题不影响浏览器开网页，但是会影响一些需要同步的程序，比如onedrive, 他认为当前无网，就自动停止同步。

1、istore是第三方插件，易有云与其他插件安装的兼容问题，只能去istore提issus
2、开启oc后Windows联网状态异常请检查，dns.msftncsi.com、www.msftncsi.com这个两个域名是否被fakedns。正常情况下只要保护这两个域名不被干扰即可保证Windows联网状态正常。
