### ISSUE TITLE
可否加个PPTP或者L2TP的VPN？

### ISSUE THREAD

**Issue by FlyingHD** [ZqinKing/wrt_relese#8]
Hi,

请问可否加个PPTP或者L2TP的VPN server？
带用户管理界面那种，允许多用户拨入那种，且彼此能互通，适合有公网IP的家庭宽带跟朋友联网打局域网游戏。谢谢

**Comment by ZqinKing** [comment]
> Hi,
> 
> 请问可否加个PPTP或者L2TP的VPN server？ 带用户管理界面那种，允许多用户拨入那种，且彼此能互通，适合有公网IP的家庭宽带跟朋友联网打局域网游戏。谢谢

可以试试wireguard

**Comment by ZqinKing** [comment]
> Hi,
> 
> 请问可否加个PPTP或者L2TP的VPN server？ 带用户管理界面那种，允许多用户拨入那种，且彼此能互通，适合有公网IP的家庭宽带跟朋友联网打局域网游戏。谢谢

如果有成品插件，可以把名称发上来，测试没问题可以进行集成。
