### ISSUE TITLE
可以增加USB热点分享吗

### ISSUE THREAD

**Issue by rabsunlei** [ZqinKing/wrt_relese#9]
RT，可以增加USB热点分享，或是上网卡等分享网络吗？谢谢。
尝试安装 kmod usb net 相关一直报错，无法安装。

**Comment by rabsunlei** [comment]
https://zhuanlan.zhihu.com/p/679573191

kmod-usb-net

kmod-usb-net-rndis

kmod-usb-net-cdc-ether

[usbutils](https://zhida.zhihu.com/search?content_id=239146353&content_type=Article&match_order=1&q=usbutils&zhida_source=entity)

备注：TTYD终端命令行模式为：

opkg update
opkg install kmod-usb-net kmod-usb-net-rndis kmod-usb-net-cdc-ether usbutils

安装报错，估计是和网络有关，大佬百忙之中抽空能添加该功能不，谢谢。
可以共享USB热或或是像中兴F50的CPE使用。

**Comment by ZqinKing** [comment]
> https://zhuanlan.zhihu.com/p/679573191
> 
> kmod-usb-net
> 
> kmod-usb-net-rndis
> 
> kmod-usb-net-cdc-ether
> 
> [usbutils](https://zhida.zhihu.com/search?content_id=239146353&content_type=Article&match_order=1&q=usbutils&zhida_source=entity)
> 
> 备注：TTYD终端命令行模式为：
> 
> opkg update opkg install kmod-usb-net kmod-usb-net-rndis kmod-usb-net-cdc-ether usbutils
> 
> 安装报错，估计是和网络有关，大佬百忙之中抽空能添加该功能不，谢谢。 可以共享USB热或或是像中兴F50的CPE使用。

就缺这几个么？

**Comment by ZqinKing** [comment]
> https://zhuanlan.zhihu.com/p/679573191
> 
> kmod-usb-net
> 
> kmod-usb-net-rndis
> 
> kmod-usb-net-cdc-ether
> 
> [usbutils](https://zhida.zhihu.com/search?content_id=239146353&content_type=Article&match_order=1&q=usbutils&zhida_source=entity)
> 
> 备注：TTYD终端命令行模式为：
> 
> opkg update opkg install kmod-usb-net kmod-usb-net-rndis kmod-usb-net-cdc-ether usbutils
> 
> 安装报错，估计是和网络有关，大佬百忙之中抽空能添加该功能不，谢谢。 可以共享USB热或或是像中兴F50的CPE使用。

试一下这个：[USB网卡](https://github.com/ZqinKing/wrt_relese/actions/runs/12367087881)

**Comment by rabsunlei** [comment]
也有可能是我的移动的网络无法支持，在正常的OP上面安装的话就不会报错，在大佬分享的固件上安装死活报错装不了，所以才来请求大佬能否安装上了分享，感谢。

是为了从USB接入安卓的网络分享，同时也可以使用如中兴F50这类CPE的USB网络接入。

**Comment by ZqinKing** [comment]
> 也有可能是我的移动的网络无法支持，在正常的OP上面安装的话就不会报错，在大佬分享的固件上安装死活报错装不了，所以才来请求大佬能否安装上了分享，感谢。
> 
> 是为了从USB接入安卓的网络分享，同时也可以使用如中兴F50这类CPE的USB网络接入。

kmod是需要编译时包含，非快照版本的固件无法后续安装，先前的包没打出来，修了一下，等编译完，从之前的链接里下载升级试一下。

**Comment by rabsunlei** [comment]
![微信图片_2024-12-18_195227_345](https://github.com/user-attachments/assets/b0241445-35d3-4d6b-b81c-70a68f3466de)
大佬方便增加一下吗？这是常规 上面安装出来后就是这样的，感谢。

参考的来源 https://zhuanlan.zhihu.com/p/679573191

**Comment by ZqinKing** [comment]
> ![微信图片_2024-12-18_195227_345](https://private-user-images.githubusercontent.com/186354597/396895586-b0241445-35d3-4d6b-b81c-70a68f3466de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTkwNDYsIm5iZiI6MTczNDU1ODc0NiwicGF0aCI6Ii8xODYzNTQ1OTcvMzk2ODk1NTg2LWIwMjQxNDQ1LTM1ZDMtNGQ2Yi1iODFjLTcwYTY4ZjM0NjZkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQyMTUyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjU3MWVlYTJhMmU3ZTUwNGEwN2M4ZjVlYzZhZmQ0MzUzYTc4MDVlNGYyNzkzY2EzZTg1MDJkOGNiMjc1MjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MgW0o_J85uxy3mJj0-4E6EWREL5ChZ246WOgVMrM69k) 大佬方便增加一下吗？这是常规 上面安装出来后就是这样的，感谢。
> 
> 参考的来源 https://zhuanlan.zhihu.com/p/679573191

已经在新的固件中增加了，你没有石嘛？

**Comment by rabsunlei** [comment]
试了，还少一个   usbutils  所以识别不到，感谢在下一个版本中添加一下，谢谢。

**Comment by rabsunlei** [comment]
![微信图片_2024-12-19_091545_449](https://github.com/user-attachments/assets/21a1be5b-81e4-41ca-b4e0-bae868983005)
自己安装就是错误代码255，这个功能能修复吗？

**Comment by ZqinKing** [comment]
> usbutils

不需要已经由busybox的lsusb提供了

**Comment by ZqinKing** [comment]
22号更新已补全CPE所需全部内核驱动。

**Comment by bitchpeng** [comment]
不得行啊  包是全了  但是设备里面没有usb0（雅典娜）

**Comment by rabsunlei** [comment]
ETH0就行了，不过要配置成WAN
